### ISSUE TITLE
bundle-el part of el-get core system?

### ISSUE THREAD

**Issue by priyadarshan** [tarao/bundle-el#1]
`bundle-el` is quite nice. Did you try to ask `el-get` mantainers to make it part of the core system?

Thank you.

**Comment by tarao** [comment]
I haven't even thought about that. It would be nice to have `bundle-el` part of `el-get` but I think there is also a disadvantage.

As long as we have `bundle-el` as a separate project, we can switch to or add support for some other backend system of package management anytime we want. Actually, I'm thinking about switching to [Cask](http://cask.readthedocs.org/en/latest/) without changing the interface of `bundle-el`.

I know that having `bundle-el` integrated into `el-get` allows us to make bootstrapping `bundle-el` and `el-get` much easier. I tried to write a simple installation script for `bundle-el` together with `el-get` but couldn't make it simple enough. (The result is in [installer branch](https://github.com/tarao/bundle-el/tree/installer).)

What else do you think are the advantages of the integration?

**Comment by priyadarshan** [comment]
I also tried `Cask`. I still prefer `el-get` for now, perhaps because it is a little less dependent on other tools (basically, only `git`).

I have found `el-get` by chance, but this is exactly what I have been looking for in the past years. It is elegant, powerful, expressive and flexible. Perhaps I am a purist, but I care a lot about its lispy beauty, too. It is very emacs-esque (while, for example, `Cask` makes me feel a little awkward in that regard.)

I just thought that `bundle-el` deserves to be known, if not used, by more people, and having it available as part of `el-get` would be a good thing. I am not sure if `el-get` maintainers would agree. They may wish to keep `el-get` as simple as possible, and have additional tools as separate repositories. Still, I feel `bundle-el` complements `el-get` nicely, and it would be useful if the two could grow together.

**Comment by priyadarshan** [comment]
To add to my previous comment, I like `bundle-el` simpler syntax. Compare, in the simplest of cases,

```
(add-to-list 'el-get-sources
             '(:name bundle :type github :pkgname "Fuco1/free-keys"))
(el-get 'sync 'bundle)

```

with

`(bundle Fuco1/free-keys)`

Thank you once again for `bundle-el`.

**Comment by priyadarshan** [comment]
@tarao Following up to this, did you see the `el-get` issue regarding the merging of your `bundle-el` package into `el-get`?

It seems the `el-get` maintainers would not mind seeing it part of the core system. That would be quite nice to many elisp users. Would you consider proving them with a pull request for the merge?

I have been using the two for quite a long time now, and they are perfect combination.

**Comment by tarao** [comment]
Thank you for posting the `el-get` issue about the integration. As I commented on the issue, I will prepare for a pull request.

**Comment by tarao** [comment]
OK, now it's done. If you wish to use the original interface (`bundle` instead of `el-get-bundle`), the master branch of `bundle-el` provides an alias for you. Thanks again!

**Comment by priyadarshan** [comment]
Thank you, and congratulations!
